name: PREPROD_RELEASE
on:
  push:
    branches:
      - main
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      ecr_repository: bitbot/accio-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@bitbot'
      - name: Update NPMRC with auth token for Github registry
        run: echo "//npm.pkg.github.com:_authToken=${{ secrets.CICD_GITHUB_PAT_READPACKAGES }}" >> ./.npmrc
        working-directory: ./
      - name: Install Packages
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CICD_GITHUB_PAT_READPACKAGES }}
      - name: Build
        run: npm run build:preprod
      - name: Run Tests
        run: npm test
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CICD_PREPROD_USER_AK }}
          aws-secret-access-key: ${{ secrets.CICD_PREPROD_USER_SK }}
          aws-region: ${{ secrets.CICD_PREPROD_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ecr_repository }}
          GITHUB_TAG: ${{ github.sha }}-preprod
          IMAGE_TAG: preprod-latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_TAG  .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
